### PR TITLE
Added Azure Install Docs + Created files for GCP + AWS 

### PR DESCRIPTION
**Pull request by omerbensaadon**
see title :D sorry for last PR, was a mistake

### CODE REVIEW

**Comment by omerbensaadon** [comment]
@snneji if you give me edit permissions I can merge these myself :D

**Comment by jncd** [comment]
Hi @omerbensaadon 
I pulled down your files to fix the merge conflicts and then did format edit on the installing-with-azure.html.md.erb page.
You can use this as a pattern for revising the other pages. Do you ever use atom or sublime as a text editor? @RichardJJG has an amazing style-checker that's fun to use and helps you write it right the first time.
Jane

P.S. I also added the two new files to the subnav.

**Comment by omerbensaadon** [comment]
I do happen to use Atom as a text editor actually and would be interested in this style-checker!

**Comment by RichardJJG** [comment]
[Style Checker](https://github.com/pivotal-cf-experimental/docs-utility-scripts/tree/master/style-checker) -- if you have any problems or queries, just shout, @omerbensaadon

**Pull request merged**
